config/routes.rb
Rails.application.routes.draw do
  resources :genres
  root 'movies#index'

  get 'movies/filter/:filter' => 'movies#index', as: :filtered_movies
  resources :movies do 
    resources :favorites, only: [:create, :destroy]
    resources :reviews
  end

  resource 'session', only: [:new, :create, :destroy]
  resources :users

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres, dependent: :destroy
  has_many :movies, through: :movie_genres

  validates :name, presence: true, uniqueness: { case_sensitive: false }

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_signin, only: [:create, :destroy, :index]
  before_action :require_admin, only: [:create, :destroy, :index]
  def index
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path, status: :see_other, notice: 'Genre added successfully'
    else
      @genres = Genre.all
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_path, status: :see_other, alert: 'Genre deleted successfully'
  end

  def show
    @genre = Genre.find(params[:id])
    @movies = @genre.movies
  end

private
  def genre_params
    params.permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/index.html.erb
<h1> Manage Genres </h1>
<div class="genres">
  <div class="add-genre">
    <div>
      <% if @genre.present? %>
        <%= render "shared/errors", object: @genre %>
      <% end %>
      <%= form_with(url: genres_path) do |f| %>
        <%= f.text_field :name%>
        <%= f.submit "Add Genre", class: "add-button" %>
      <% end %>
    </div>
  </div>
  <div class="all-genres">
    <ul  class="list-group ">
      <li class="list-group-item active list-group-item-primary"> 
          <span class="name">All Genres</span>
      </li>
      <% @genres.each do |genre|%>
        <li class="list-group-item align-middle"> 
          <div class="row">
            <div class="name align-middle col-md-9">
              <%= link_to genre.name, genre %>
            </div>
            <div class="col-md-3 text-end">
              <%= button_to "Delete", genre_path(genre), method: :delete, class: "btn btn-danger" %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </section>
</div>

app/views/genres/show.html.erb
<h1> <%= @genre.name %> Movies </h1>
<%= render "shared/movie_list", movies:@movies %>