config/routes.rb
Rails.application.routes.draw do
  resources :genres
  root 'movies#index'

  get 'movies/filter/:filter' => 'movies#index', as: :filtered_movies
  resources :movies do 
    resources :favorites, only: [:create, :destroy]
    resources :reviews
  end

  resource 'session', only: [:new, :create, :destroy]
  resources :users

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
      <%=flash[:notice]%>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
      <%=flash[:alert]%>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div>
    Copyright AB Code Factory Corp Pvt Ltd &copy; <%=Time.now.year%> 
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag('logo'), root_path %>
    <ul class="left">
      <li>
        <%= nav_link_to "Released", movies_path %>
      </li>
      <li>
        <%= nav_link_to "Upcoming", filtered_movies_path(:upcoming) %>
      </li>
      <li>
        
        <%= nav_link_to "Hits", filtered_movies_path(:hits) %>
      </li>
      <li>
        <%= nav_link_to "Flops", filtered_movies_path(:flops) %>
      </li>
      <% if current_user_admin? %>
        <li>
          <%= nav_link_to "New Movie", new_movie_path %>
        </li>
        <li>
          <%= nav_link_to "All Users", users_path %>
        </li>
        <li>
          <%= nav_link_to "Manage Genres", genres_path %>
        </li>
      <% end %>
    </ul>
    <ul class="right">
      <% if is_logged_in? %>
        <li>
          <!-- <%= profile_image current_user %> -->
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "⚙", edit_user_path(current_user)%>
        </li>
        <li>
          <%= link_to "🚪", logout_path, data: {turbo_method: :delete} %>
        </li>
      <% else %>
        <li>
          <%= link_to "Login", login_path, class: "button" %>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="content">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>